In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import gmaps
from config import g_key

In [2]:
df=pd.DataFrame(pd.read_csv("cleaned_data.csv"))

In [4]:
states_df=pd.DataFrame(pd.read_csv("world_country_and_usa_states_latitude_and_longitude_values.csv"))
states_df.head()
states=states_df["usa_state"].tolist()
states_df

,usa_state_code,usa_state_latitude,usa_state_longitude,usa_state
0,AK,63.588753,-154.493062,Alaska
1,AL,32.318231,-86.902298,Alabama
2,AR,35.201050,-91.831833,Arkansas
3,AZ,34.048928,-111.093731,Arizona
4,CA,36.778261,-119.417932,California
5,CO,39.550051,-105.782067,Colorado
6,CT,41.603221,-73.087749,Connecticut
7,DC,38.905985,-77.033418,District of Columbia
8,DE,38.910832,-75.527670,Delaware
9,FL,27.664827,-81.515754,Florida
10,GA,32.157435,-82.907123,Georgia
11,HI,19.898682,-155.665857,Hawaii
12,IA,41.878003,-93.097702,Iowa
13,ID,44.068202,-114.742041,Idaho
14,IL,40.633125,-89.398528,Illinois
15,IN,40.551217,-85.602364,Indiana
16,KS,39.011902,-98.484246,Kansas
17,KY,37.839333,-84.270018,Kentucky
18,LA,31.244823,-92.145024,Louisiana
19,MA,42.407211,-71.382437,Massachusetts
20,MD,39.045755,-76.641271,Maryland
21,ME,45.253783,-69.445469,Maine
22,MI,44.314844,-85.602364,Michigan
23,MN,46.729553,-94.685900,Minnesota
24,MO,37.964253,-91.831833,Missouri
25,MS,32.354668,-89.398528,Mississippi
26,MT,46.879682,-110.362566,Montana
27,NC,35.759573,-79.019300,North Carolina
28,ND,47.551493,-101.002012,North Dakota
29,NE,41.492537,-99.901813,Nebraska
30,NH,43.193852,-71.572395,New Hampshire
31,NJ,40.058324,-74.405661,New Jersey
32,NM,34.972730,-105.032363,New Mexico
33,NV,38.802610,-116.419389,Nevada
34,NY,43.299428,-74.217933,New York
35,OH,40.417287,-82.907123,Ohio
36,OK,35.007752,-97.092877,Oklahoma
37,OR,43.804133,-120.554201,Oregon
38,PA,41.203322,-77.194525,Pennsylvania
39,PR,18.220833,-66.590149,Puerto Rico
40,RI,41.580095,-71.477429,Rhode Island
41,SC,33.836081,-81.163725,South Carolina
42,SD,43.969515,-99.901813,South Dakota
43,TN,35.517491,-86.580447,Tennessee
44,TX,31.968599,-99.901813,Texas
45,UT,39.320980,-111.093731,Utah
46,VA,37.431573,-78.656894,Virginia
47,VT,44.558803,-72.577841,Vermont
48,WA,47.751074,-120.740139,Washington
49,WI,43.784440,-88.787868,Wisconsin
50,WV,38.597626,-80.454903,West Virginia
51,WY,43.075968,-107.290284,Wyoming

In [5]:
df.head()

,Unnamed: 0,Dis No,Year,Disaster Subgroup,Disaster Type,Disaster Subtype,Disaster Subsubtype,Location,Origin,Latitude,Longitude,Start Year,Start Month,Start Day,End Year,End Month,End Day,Total Deaths
0,175,1990-0346-USA,1990,Meteorological,Storm,Convective storm,Severe storm,"Oklahoma, Kansas, Nebraska, Missouri, Iowa, Il...",NaN,NaN,NaN,1990,3,13.0,1990,3.0,17.0,15.0
1,176,1990-0357-USA,1990,Meteorological,Storm,Convective storm,Severe storm,"Texas, Oklahoma, Arkansas, Virginie, Caroline ...",NaN,NaN,NaN,1990,5,1.0,1990,5.0,9.0,13.0
2,177,1990-0359-USA,1990,Meteorological,Storm,Convective storm,Severe storm,"Texas, Oklahoma, Arkansas, Kansas, Missouri, I...",NaN,NaN,NaN,1990,5,14.0,1990,5.0,17.0,NaN
3,178,1990-0360-USA,1990,Meteorological,Storm,Convective storm,Severe storm,"Nebraska, Iowa, Kansas, Missouri, Texas, Oklah...",NaN,NaN,NaN,1990,5,18.0,1990,5.0,21.0,NaN
4,179,1990-0363-USA,1990,Meteorological,Storm,Convective storm,Severe storm,"Colorado, Kansas, Missouri, Indiana, Kentucky",NaN,NaN,NaN,1990,6,6.0,1990,6.0,8.0,NaN

In [6]:
cs_states=df["Location"].tolist()
test=cs_states[5] #Texas
state_counts=[]
for st in states:
    count=0
    for string in cs_states:
        if str(string).count(st)>0:
            count=count+1
    state_counts.append(count)

In [7]:
states_df["State Counts"]=state_counts
states_df

,usa_state_code,usa_state_latitude,usa_state_longitude,usa_state,State Counts
0,AK,63.588753,-154.493062,Alaska,7
1,AL,32.318231,-86.902298,Alabama,106
2,AR,35.201050,-91.831833,Arkansas,103
3,AZ,34.048928,-111.093731,Arizona,27
4,CA,36.778261,-119.417932,California,104
5,CO,39.550051,-105.782067,Colorado,70
6,CT,41.603221,-73.087749,Connecticut,47
7,DC,38.905985,-77.033418,District of Columbia,17
8,DE,38.910832,-75.527670,Delaware,34
9,FL,27.664827,-81.515754,Florida,82
10,GA,32.157435,-82.907123,Georgia,99
11,HI,19.898682,-155.665857,Hawaii,5
12,IA,41.878003,-93.097702,Iowa,89
13,ID,44.068202,-114.742041,Idaho,16
14,IL,40.633125,-89.398528,Illinois,134
15,IN,40.551217,-85.602364,Indiana,108
16,KS,39.011902,-98.484246,Kansas,124
17,KY,37.839333,-84.270018,Kentucky,102
18,LA,31.244823,-92.145024,Louisiana,99
19,MA,42.407211,-71.382437,Massachusetts,50
20,MD,39.045755,-76.641271,Maryland,65
21,ME,45.253783,-69.445469,Maine,38
22,MI,44.314844,-85.602364,Michigan,67
23,MN,46.729553,-94.685900,Minnesota,74
24,MO,37.964253,-91.831833,Missouri,143
25,MS,32.354668,-89.398528,Mississippi,99
26,MT,46.879682,-110.362566,Montana,30
27,NC,35.759573,-79.019300,North Carolina,97
28,ND,47.551493,-101.002012,North Dakota,34
29,NE,41.492537,-99.901813,Nebraska,75
30,NH,43.193852,-71.572395,New Hampshire,34
31,NJ,40.058324,-74.405661,New Jersey,74
32,NM,34.972730,-105.032363,New Mexico,34
33,NV,38.802610,-116.419389,Nevada,27
34,NY,43.299428,-74.217933,New York,104
35,OH,40.417287,-82.907123,Ohio,112
36,OK,35.007752,-97.092877,Oklahoma,127
37,OR,43.804133,-120.554201,Oregon,29
38,PA,41.203322,-77.194525,Pennsylvania,94
39,PR,18.220833,-66.590149,Puerto Rico,0
40,RI,41.580095,-71.477429,Rhode Island,39
41,SC,33.836081,-81.163725,South Carolina,68
42,SD,43.969515,-99.901813,South Dakota,47
43,TN,35.517491,-86.580447,Tennessee,95
44,TX,31.968599,-99.901813,Texas,202
45,UT,39.320980,-111.093731,Utah,14
46,VA,37.431573,-78.656894,Virginia,98
47,VT,44.558803,-72.577841,Vermont,33
48,WA,47.751074,-120.740139,Washington,51
49,WI,43.784440,-88.787868,Wisconsin,78
50,WV,38.597626,-80.454903,West Virginia,46
51,WY,43.075968,-107.290284,Wyoming,27

In [8]:
gmaps.configure(api_key=g_key)
locs=states_df[["usa_state_latitude", "usa_state_longitude"]]
myfig=gmaps.figure()
heatmap = gmaps.heatmap_layer(locs, weights=state_counts, 
                                 dissipating=False,max_intensity=states_df["State Counts"].max()-40,
                                 point_radius=1.5)
myfig.add_layer(heatmap)
myfig

Figure(layout=FigureLayout(height='420px'))

In [51]:
info_box_template = """
<dl>
<dt>Disaster Count</dt><dd>{State Counts}</dd>
<dt>State</dt><dd>{usa_state}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
state_info = [info_box_template.format(**row) for index, row in states_df.iterrows()]

In [55]:
marker_layer = gmaps.marker_layer(locs, info_box_content=state_info)
myfig.add_layer(marker_layer)
myfig

Figure(layout=FigureLayout(height='420px'))